### ISSUE TITLE
bblast python package issue during installation of co-anno

### ISSUE THREAD

**Issue by El-Castor** [gturco/find_cns#15]
Hi, 

I trying to install by hand (bootstrap doesn't work) your tools. But It seems that I hhave some issue during the co-anno package install following these command : 

```bash
cd pipeline/coann/brents_bpbio/biostuff/co-anno/
python setup.py install
```

here you can see the error:

```bash
Searching for bblast
Reading https://pypi.org/simple/bblast/
Couldn't find index page for 'bblast' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for bblast
error: Could not find suitable distribution for Requirement.parse('bblast')
```

Do you have any idea to bypass this issue?

thanks in advance

**Comment by El-Castor** [comment]
I doesn't find the bblast package, where can I find it please ?

**Comment by gturco** [comment]
bblast is part of bpbio package found here: https://code.google.com/archive/p/bpbio/
